In [1]:
#numpy

In [8]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [9]:
import numpy as np

In [10]:
#creating array

In [11]:
sample_array = np.array([1,2,3,4])

In [12]:
sample_array

array([1, 2, 3, 4])

In [13]:
sample_array2 = np.array([5,6,7,8])

In [14]:
sample_array2

array([5, 6, 7, 8])

In [15]:
#2D Array
sample_array_2 = np.array([[1,2],[3,4]])

In [16]:
sample_array_2

array([[1, 2],
       [3, 4]])

In [17]:
#3D Tensor (2 matrices, each with 2 rows and 2 columns)

In [18]:
sample_tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [19]:
sample_tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [20]:
"""
Dimension:
0D Array(Scalar) 
1D Array(Vector)
2D Array(Matrix) (rows,columns)
3D Array(Tensor) (page, row, column)
"""

'\nDimension:\n0D Array(Scalar) \n1D Array(Vector)\n2D Array(Matrix) (rows,columns)\n3D Array(Tensor) (page, row, column)\n'

In [21]:
#Array Properties

In [22]:
sample_array = np.array([[1,2,3],[4,5,6]])

In [23]:
sample_array

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
#shape

In [25]:
sample_array.shape

(2, 3)

In [26]:
#dimension

In [27]:
sample_array.ndim

2

In [28]:
#total elements

In [29]:
sample_array.size

6

In [30]:
#data type

In [31]:
sample_array.dtype

dtype('int64')

In [32]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [33]:
a.shape

(2, 2, 2)

In [34]:
a.ndim

3

In [35]:
a.size

8

In [36]:
a.dtype

dtype('int64')

In [37]:
#Special Array

In [38]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [41]:
np.arange(0,20,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [42]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [43]:
#Indexing & Slicing

In [44]:
sample_array = np.array([10,20,30,40])

In [45]:
sample_array

array([10, 20, 30, 40])

In [46]:
sample_array[0]

np.int64(10)

In [47]:
sample_array[2]

np.int64(30)

In [48]:
sample_array[-1]

np.int64(40)

In [49]:
sample_array[1:3]

array([20, 30])

In [50]:
#Array Operations

In [51]:
a = np.array([1,2,3])

In [52]:
b = np.array([4,5,6])

In [53]:
a

array([1, 2, 3])

In [55]:
b

array([4, 5, 6])

In [56]:
a + b

array([5, 7, 9])

In [57]:
a - b

array([-3, -3, -3])

In [58]:
a * b

array([ 4, 10, 18])

In [59]:
a / b

array([0.25, 0.4 , 0.5 ])

In [62]:
a = np.array([10,20,30])

In [63]:
b = np.array([40,50,60])

In [64]:
a + b

array([50, 70, 90])

In [65]:
a - b

array([-30, -30, -30])

In [66]:
a * b

array([ 400, 1000, 1800])

In [67]:
a / b

array([0.25, 0.4 , 0.5 ])

In [68]:
#Mathematical Function

In [69]:
sample_array = np.array([1,4,9])

In [70]:
sample_array

array([1, 4, 9])

In [71]:
np.sqrt(sample_array)

array([1., 2., 3.])

In [72]:
arr = np.array([34,56,90])

In [73]:
np.sqrt(arr)

array([5.83095189, 7.48331477, 9.48683298])

In [74]:
np.exp(sample_array)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [75]:
np.exp(arr)

array([5.83461743e+14, 2.09165950e+24, 1.22040329e+39])

In [76]:
np.log(sample_array)

array([0.        , 1.38629436, 2.19722458])

In [77]:
np.log(arr)

array([3.52636052, 4.02535169, 4.49980967])

In [78]:
arr1 = np.array([100,213,454])

In [79]:
np.log(arr1)

array([4.60517019, 5.36129217, 6.1180972 ])

In [61]:
#Stastical Functions

In [62]:
a = np.array([1,2,3,4,5])

In [63]:
a

array([1, 2, 3, 4, 5])

In [64]:
np.mean(a)

np.float64(3.0)

In [65]:
np.median(a)

np.float64(3.0)

In [66]:
np.std(a)

np.float64(1.4142135623730951)

In [67]:
np.min(a)

np.int64(1)

In [68]:
np.max(a)

np.int64(5)

In [69]:
#Reshaping Arrays

In [70]:
sample_array = np.arange(6)

In [71]:
sample_array

array([0, 1, 2, 3, 4, 5])

In [72]:
reshaped = sample_array.reshape(2,3)

In [73]:
reshaped

array([[0, 1, 2],
       [3, 4, 5]])

In [74]:
#Flattening

In [75]:
sample_array = np.array([[1,2],[3,4]])

In [76]:
sample_array

array([[1, 2],
       [3, 4]])

In [77]:
sample_array.flatten()

array([1, 2, 3, 4])

In [78]:
a = np.array([[[1,2],[3,4],[5,6],[7,8]]])

In [79]:
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [80]:
#Joining Arrays

In [81]:
a = np.array([1,2])

In [82]:
b = np.array([3,4])

In [83]:
a

array([1, 2])

In [84]:
b


array([3, 4])

In [87]:
np.concatenate((a,b))

array([1, 2, 3, 4])

In [88]:
#Splitting Arrays

In [89]:
sample_array = np.array([1,2,3,4])

In [90]:
sample_array

array([1, 2, 3, 4])

In [91]:
np.array_split(sample_array,2)

[array([1, 2]), array([3, 4])]

In [92]:
#Random Module

In [93]:
np.random.rand(3)

array([0.37980253, 0.93965281, 0.5012285 ])

In [94]:
np.random.randint(1,10,5)

array([6, 4, 5, 5, 5], dtype=int32)

In [95]:
#Axis Concept

In [97]:
sample_array = np.array([[1,2],[3,4]])

In [98]:
sample_array

array([[1, 2],
       [3, 4]])

In [99]:
np.sum(sample_array, axis = 0)

array([4, 6])

In [100]:
np.sum(sample_array, axis = 1)

array([3, 7])

In [101]:
#NaN & Missing Values

In [80]:
sample_array = np.array([1,np.nan,3])

In [81]:
sample_array

array([ 1., nan,  3.])

In [82]:
np.isnan(sample_array)

array([False,  True, False])